<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MeAndAI.Operations.Packaging</RootNamespace>
    <SelfContained>false</SelfContained>
    <RollForward>LatestPatch</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/MeAndAI.Operations.Domain/MeAndAI.Operations.Domain.csproj" />
  </ItemGroup>
</Project>
