<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MeAndAI.Operations.Governance</RootNamespace>
    <SelfContained>false</SelfContained>
    <RollForward>LatestPatch</RollForward>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../MeAndAI.Operations.Domain/MeAndAI.Operations.Domain.csproj" />
    <ProjectReference Include="../MeAndAI.Operations.Infrastructure/MeAndAI.Operations.Infrastructure.csproj" />
  </ItemGroup>
</Project>
